import { defineConfig, devices } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Read base URL from .dev-context file
 * This file is auto-generated by `npm run dev`
 */
function getBaseURL(): string {
  try {
    const devContextPath = path.join(__dirname, '../../.dev-context');
    const content = fs.readFileSync(devContextPath, 'utf-8');
    const match = content.match(/Slides:\s+http:\/\/localhost:(\d+)/);
    if (match) {
      return `http://localhost:${match[1]}`;
    }
  } catch {
    // File doesn't exist or couldn't be read
  }
  return 'http://localhost:6550'; // Default slides port
}

/**
 * Playwright configuration for Slides E2E tests.
 *
 * Tests are sequential (not parallel) because they share state:
 * - Tests create slides that subsequent tests need to access
 * - Tests switch between users to verify permissions
 *
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './tests',

  // Run tests sequentially - they share state
  fullyParallel: false,
  workers: 1,

  // No retries - we want to see failures immediately
  retries: 0,

  // Reporter configuration
  reporter: [
    ['list'],
    ['html', { open: 'never' }],
  ],

  // Timeout configuration
  timeout: 60_000, // 60 seconds per test
  expect: {
    timeout: 10_000, // 10 seconds for assertions
  },

  // Shared settings for all projects
  use: {
    baseURL: getBaseURL(),

    // Collect trace on first retry
    trace: 'on-first-retry',

    // Screenshot on failure
    screenshot: 'only-on-failure',

    // Video on failure
    video: 'on-first-retry',

    // Action timeout
    actionTimeout: 10_000,

    // Navigation timeout
    navigationTimeout: 30_000,
  },

  projects: [
    {
      name: 'slides-e2e',
      testMatch: /.*\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],

  // Output directory for test artifacts
  outputDir: './tests/test-results',
});
