import { defineConfig, devices } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Pin the suite's process zone, and pin it somewhere HOSTILE — deliberately not
 * UTC, and deliberately not a zone any fixture configures.
 *
 * The public `/schedule` formats deadlines on the server and ships no
 * JavaScript, so its dates are final; there is no client pass to correct them
 * the way every member-facing view gets for free. `scheduleRows.ts` therefore
 * has to ignore the process zone completely and read only the course's
 * configured zone. This pin is what makes that property TESTABLE.
 *
 * UTC would be the obvious pin — it is what production runs (alpine, no TZ) —
 * and it is the one value that cannot work here. Under UTC a renderer that
 * wrongly consults the process zone produces byte-identical output to one that
 * correctly uses `dayjs.utc`, so every assertion passes and the regression is
 * invisible. Verified, not assumed: reverting `dayjs.utc(x)` to `dayjs(x)` keeps
 * the whole schedule spec green under TZ=UTC and fails it under this pin, on
 * both the UTC-fallback string and the naive-timestamp parse.
 *
 * Pacific/Honolulu specifically: ten hours from UTC, so a date-boundary error
 * shows as a different day rather than a different hour; no DST, so the suite
 * does not change behaviour twice a year; and it is not America/New_York, which
 * the fixtures configure — a pin equal to the fixture's own zone would let a
 * broken renderer pass by coincidence.
 *
 * Set HERE rather than with `process.env.TZ = ...` inside a spec: Node caches
 * the zone on first use, so a mid-process assignment is unreliable. Workers are
 * forked from this process and read TZ fresh at startup, which makes assigning
 * it at config load equivalent to setting it at launch.
 */
process.env.TZ = 'Pacific/Honolulu';

/**
 * Read base URL from .dev-context file
 * This file is auto-generated by `npm run dev`
 */
function getBaseURL(): string {
  try {
    const devContextPath = path.join(__dirname, '../../.dev-context');
    const content = fs.readFileSync(devContextPath, 'utf-8');
    const match = content.match(/Pages:\s+http:\/\/localhost:(\d+)/);
    if (match) {
      return `http://localhost:${match[1]}`;
    }
  } catch {
    // File doesn't exist or couldn't be read
  }
  return 'http://localhost:7100'; // Default pages port
}

/**
 * Playwright configuration for Pages E2E tests.
 *
 * Mirrors the slides app's harness: tests run against the already-running dev
 * stack (npm run dev) and authenticate via the /test-login route.
 *
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './tests',

  // Run tests sequentially - they share the seeded dev database
  fullyParallel: false,
  workers: 1,

  // No retries - we want to see failures immediately
  retries: 0,

  // Reporter configuration
  reporter: [['list'], ['html', { open: 'never' }]],

  // Timeout configuration
  timeout: 60_000, // 60 seconds per test
  expect: {
    timeout: 10_000, // 10 seconds for assertions
  },

  // Shared settings for all projects
  use: {
    baseURL: getBaseURL(),

    // Collect trace on first retry
    trace: 'on-first-retry',

    // Screenshot on failure
    screenshot: 'only-on-failure',

    // Video on failure
    video: 'on-first-retry',

    // Action timeout
    actionTimeout: 10_000,

    // Navigation timeout
    navigationTimeout: 30_000,
  },

  projects: [
    {
      name: 'pages-e2e',
      testMatch: /.*\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],

  // Output directory for test artifacts
  outputDir: './tests/test-results',
});
