/**
 * Generate the `.github/workflows/classroom.yml` GitHub Actions workflow from a
 * repository's autograding tests, mirroring GitHub Classroom. Each test becomes
 * a grader step (the open-source `classroom-resources` graders); a reporter step
 * posts the familiar check-run; and a final callback step reports per-test
 * pass/fail back to Classmoji.
 *
 * Dependency-free: user-supplied strings are embedded via JSON.stringify, which
 * produces valid YAML double-quoted scalars (YAML decodes the same escapes as
 * JSON), so arbitrary commands / inputs / expected output are safe.
 */

export interface WorkflowTestInput {
  name: string;
  method: 'COMMAND' | 'IO' | 'PYTHON' | 'JAVA' | 'NODE' | 'C' | 'CPP';
  setup_command?: string | null;
  run_command?: string | null;
  input?: string | null;
  expected_output?: string | null;
  comparison_method?: 'INCLUDED' | 'EXACT' | 'REGEX' | null;
  timeout?: number | null;
  points?: number | null;
}

export interface GenerateWorkflowOptions {
  /**
   * Results are reported via Trigger.dev's public REST API rather than a direct
   * call to the Classmoji webapp. Trigger's API is reachable from GitHub Actions
   * and routes the run to the local dev worker (or deployed workers), which write
   * to the DB — so this works in local dev with no public webapp URL / tunnel.
   */
  triggerUrl?: string | null; // full task-trigger endpoint
  triggerToken?: string | null; // task-scoped public access token
  classroomSlug?: string | null; // included in the payload + resolves the repo
  hmacToken?: string | null; // per-classroom HMAC (verifyAutogradeCallbackToken)
}

/** YAML double-quoted scalar (JSON string is a valid YAML scalar). */
function yamlStr(value: string): string {
  return JSON.stringify(value);
}

/** Stable, unique, lowercase step id from a test name + index. */
function stepId(name: string, index: number): string {
  const base = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return base ? `${base}-${index}` : `test-${index}`;
}

// NOTE: the io-grader validates against ['exact', 'contains', 'regex'] — its
// own action.yml docs say "included" but the code rejects it, so "Included"
// must be emitted as `contains`.
const COMPARISON_MAP: Record<string, string> = {
  INCLUDED: 'contains',
  EXACT: 'exact',
  REGEX: 'regex',
};

export function generateClassroomWorkflow(
  tests: WorkflowTestInput[],
  options: GenerateWorkflowOptions = {}
): string {
  const ids = tests.map((t, i) => stepId(t.name, i));
  const lines: string[] = [];

  lines.push('# Generated by Classmoji — do not edit by hand.');
  lines.push('# Defines autograding tests that run on every push via GitHub Actions.');
  lines.push('name: Autograding Tests');
  lines.push('on:');
  lines.push('  push:');
  lines.push('    branches: ["*"]');
  lines.push('  workflow_dispatch:');
  lines.push('permissions:');
  lines.push('  checks: write');
  lines.push('  actions: read');
  lines.push('  contents: read');
  lines.push('jobs:');
  lines.push('  run-autograding-tests:');
  lines.push('    runs-on: ubuntu-latest');
  lines.push("    if: github.actor != 'github-classroom[bot]'");
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');

  tests.forEach((test, i) => {
    const id = ids[i];
    const timeout = test.timeout && test.timeout > 0 ? test.timeout : 10;
    const maxScore = test.points && test.points > 0 ? test.points : 1;
    lines.push('');
    lines.push(`      - name: ${yamlStr(test.name)}`);
    lines.push(`        id: ${id}`);
    // Keep the workflow running through a failing test so later tests + the
    // reporter still execute; per-test pass/fail is read from steps.<id>.outcome.
    lines.push('        continue-on-error: true');

    if (test.method === 'IO') {
      lines.push('        uses: classroom-resources/autograding-io-grader@v1');
      lines.push('        with:');
      lines.push(`          test-name: ${yamlStr(test.name)}`);
      lines.push(`          command: ${yamlStr(test.run_command ?? '')}`);
      lines.push(`          input: ${yamlStr(test.input ?? '')}`);
      lines.push(`          expected-output: ${yamlStr(test.expected_output ?? '')}`);
      lines.push(
        `          comparison-method: ${COMPARISON_MAP[test.comparison_method ?? 'INCLUDED'] ?? 'included'}`
      );
      lines.push(`          timeout: ${timeout}`);
      lines.push(`          max-score: ${maxScore}`);
    } else {
      // COMMAND + language presets all compile to the command grader.
      lines.push('        uses: classroom-resources/autograding-command-grader@v1');
      lines.push('        with:');
      lines.push(`          test-name: ${yamlStr(test.name)}`);
      if (test.setup_command) {
        lines.push(`          setup-command: ${yamlStr(test.setup_command)}`);
      }
      lines.push(`          command: ${yamlStr(test.run_command ?? '')}`);
      lines.push(`          timeout: ${timeout}`);
      lines.push(`          max-score: ${maxScore}`);
    }
  });

  // Reporter — the familiar GitHub Classroom check-run summary.
  if (tests.length) {
    lines.push('');
    lines.push('      - name: Autograding Reporter');
    lines.push('        uses: classroom-resources/autograding-grading-reporter@v1');
    lines.push('        env:');
    ids.forEach((id, i) => {
      lines.push(`          ${id.toUpperCase()}_RESULTS: "\${{ steps.${ids[i]}.outputs.result }}"`);
    });
    lines.push('        with:');
    lines.push(`          runners: ${ids.join(',')}`);
  }

  // Report per-test pass/fail to Classmoji by triggering the
  // `ingest_autograde_result` task via Trigger.dev's REST API. We send each
  // grader's `outputs.result` (a base64-encoded JSON with the real pass/fail
  // status) — NOT `steps.<id>.outcome`, which is always "success" because the
  // graders catch failures internally and exit 0.
  if (options.triggerUrl && options.triggerToken && tests.length) {
    // Each entry is a line of a JSON object inside a YAML literal block scalar
    // (indented 12 spaces, under the 10-space `AUTOGRADE_RESULTS:` key).
    const entries = tests.map(
      (t, i) =>
        `            ${JSON.stringify(ids[i])}: {"name": ${yamlStr(t.name)}, "result": "\${{ steps.${ids[i]}.outputs.result }}"}`
    );
    lines.push('');
    lines.push('      - name: Report results to Classmoji');
    lines.push('        if: always()');
    lines.push('        env:');
    lines.push('          AUTOGRADE_RESULTS: |');
    lines.push('            {');
    lines.push(entries.join(',\n'));
    lines.push('            }');
    lines.push('        run: |');
    lines.push('          payload=$(jq -n \\');
    lines.push('            --arg repo "${{ github.repository }}" \\');
    lines.push('            --arg sha "${{ github.sha }}" \\');
    lines.push('            --arg run_id "${{ github.run_id }}" \\');
    lines.push('            --arg actor "${{ github.actor }}" \\');
    lines.push(`            --arg slug ${yamlStr(options.classroomSlug ?? '')} \\`);
    lines.push(`            --arg token ${yamlStr(options.hmacToken ?? '')} \\`);
    lines.push('            --argjson results "$AUTOGRADE_RESULTS" \\');
    lines.push(
      "            '{payload: {classroomSlug:$slug, repo:$repo, sha:$sha, run_id:$run_id, actor:$actor, token:$token, results:$results}}')"
    );
    lines.push(`          curl -sS -X POST ${yamlStr(options.triggerUrl)} \\`);
    lines.push(`            -H ${yamlStr(`Authorization: Bearer ${options.triggerToken}`)} \\`);
    lines.push('            -H "Content-Type: application/json" \\');
    lines.push('            -d "$payload" || true');
  }

  return lines.join('\n') + '\n';
}
