name: 📚 Documentation
description: Report documentation issues or request documentation improvements
title: "📚 Documentation: "
labels: ["documentation"]
assignees: ["timofei7", "pape98"]
body:
  - type: textarea
    id: documentation-issue
    attributes:
      label: Documentation Issue
      description: Describe the documentation issue or improvement you'd like to see
      placeholder: |
        What documentation is missing, unclear, or incorrect?
        What would you like to see added or improved?
    validations:
      required: true

  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Content
      description: If you have specific suggestions for the documentation content, please provide them here
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or examples that might be helpful
    validations:
      required: false
