#!/bin/bash
# scripts/dev.sh - Development server wrapper with devport support
# Sources devport-env.sh to configure ports, then starts all services

set -e

# Get the directory where this script lives
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_DIR"

# Step 1: Load environment variables from local .env
if [ -f "$PROJECT_DIR/.env" ]; then
  echo "📄 Loading environment from .env..."
  set -a  # Auto-export all variables
  source "$PROJECT_DIR/.env"
  set +a
else
  echo "⚠️  No .env file found! Copy .env.example to .env first."
  echo "   cp .env.example .env"
  exit 1
fi

# Step 2: Source devport environment AFTER loading .env
# This OVERWRITES .env values for DATABASE_URL, WEBAPP_URL, etc. if devport is active
source "$SCRIPT_DIR/devport-env.sh"

# Step 3: Export all devport vars so they're available to subprocesses
export DATABASE_URL WEBAPP_URL HOST_URL QUIZ_AGENT_URL AI_AGENT_URL SLIDES_URL PAGES_URL
export WEBAPP_PORT HOOK_PORT QUIZ_AGENT_PORT SLIDES_PORT PAGES_PORT
export DEVPORT_ID DEVPORT_NAME

# Step 4: Clean up orphaned processes from previous sessions of THIS devport only
# Only kills ports assigned to current DEVPORT_ID, not other devports or main
cleanup_ports() {
  local ports="$WEBAPP_PORT $HOOK_PORT $QUIZ_AGENT_PORT $SLIDES_PORT $PAGES_PORT"
  local killed=false
  for port in $ports; do
    if lsof -ti:$port >/dev/null 2>&1; then
      lsof -ti:$port | xargs kill -9 2>/dev/null && killed=true
    fi
  done
  if [ "$killed" = true ]; then
    echo "🧹 Cleaned up orphaned processes on ports: $ports"
    sleep 1  # Give ports time to release
  fi
}

cleanup_ports

# Check branch (prompts on main/staging)
"$SCRIPT_DIR/check-branch.sh"

# Set log file name and prefixes based on devport
if [ -n "$DEVPORT_NAME" ]; then
  LOG_FILE="/tmp/classmoji-dev-${DEVPORT_NAME}.log"
  PREFIX_BASE="web:$DEVPORT_NAME,slides:$DEVPORT_NAME,pages:$DEVPORT_NAME,hook:$DEVPORT_NAME,trigger:$DEVPORT_NAME,smee-gh,smee-stripe,quiz:$DEVPORT_NAME"
  DB_NAME="classmoji_${DEVPORT_NAME//-/_}"
else
  LOG_FILE="/tmp/classmoji-dev.log"
  PREFIX_BASE="web,slides,pages,hook,trigger,smee-gh,smee-stripe,quiz"
  DB_NAME="classmoji"
fi

# Singleton pattern for webhook fanout: only start if port 4000 is not already in use
# This allows any devport to start the fanout, but prevents duplicates
if lsof -i :4000 -sTCP:LISTEN >/dev/null 2>&1; then
  echo "🔀 Webhook fanout already running on port 4000 (started by another session)"
  RUN_FANOUT=false
  PREFIX="$PREFIX_BASE"
else
  echo "🔀 Starting webhook fanout on port 4000"
  RUN_FANOUT=true
  PREFIX="$PREFIX_BASE,fanout"
fi

# Write context file for Claude to know the current dev environment
cat > "$PROJECT_DIR/.dev-context" << EOF
# Dev Environment Context (auto-generated by npm run dev)
# Last started: $(date)

DEVPORT_NAME=${DEVPORT_NAME:-main}
DEVPORT_ID=${DEVPORT_ID:-0}

## Services Running:
- Webapp:     http://localhost:$WEBAPP_PORT
- Slides:     http://localhost:$SLIDES_PORT
- Pages:      http://localhost:$PAGES_PORT
- Hook:       http://localhost:$HOOK_PORT
- Quiz Agent: http://localhost:$QUIZ_AGENT_PORT

## Database:
- Name: $DB_NAME
- URL:  postgresql://classmoji:classmoji@localhost:5433/$DB_NAME

## Logs:
- File: $LOG_FILE
- View: tail -f $LOG_FILE
EOF

# Build the concurrently command
# Since we've already exported all env vars (.env + devport overrides),
# we can call turbo directly.
# Fanout only runs if port 4000 is free (singleton pattern)

# Check if ai-agent submodule is available
AI_AGENT_CMD=""
if [ -f "apps/ai-agent/package.json" ]; then
  AI_AGENT_CMD="PORT=$QUIZ_AGENT_PORT turbo run dev --filter=@classmoji/ai-agent --log-prefix=none"
else
  echo "⚠️  ai-agent submodule not initialized — skipping AI agent service"
fi

if [ "$RUN_FANOUT" = true ]; then
  if [ -n "$AI_AGENT_CMD" ]; then
    concurrently \
      --names "$PREFIX" \
      --prefix-colors "cyan,magenta,yellow,green,blue,red,white,gray,bgMagenta" \
      "PORT=$WEBAPP_PORT turbo run web:dev --log-prefix=none" \
      "PORT=$SLIDES_PORT turbo run slides:dev --filter=@classmoji/slides --log-prefix=none" \
      "PORT=$PAGES_PORT turbo run pages:dev --filter=@classmoji/pages --log-prefix=none" \
      "PORT=$HOOK_PORT turbo run hook:dev --log-prefix=none" \
      "turbo run trigger:dev --log-prefix=none" \
      "turbo run hook:github --log-prefix=none" \
      "turbo run hook:stripe --log-prefix=none" \
      "$AI_AGENT_CMD" \
      "node $SCRIPT_DIR/webhook-fanout.js" \
      2>&1 | tee "$LOG_FILE"
  else
    concurrently \
      --names "$PREFIX" \
      --prefix-colors "cyan,magenta,yellow,green,blue,red,white,bgMagenta" \
      "PORT=$WEBAPP_PORT turbo run web:dev --log-prefix=none" \
      "PORT=$SLIDES_PORT turbo run slides:dev --filter=@classmoji/slides --log-prefix=none" \
      "PORT=$PAGES_PORT turbo run pages:dev --filter=@classmoji/pages --log-prefix=none" \
      "PORT=$HOOK_PORT turbo run hook:dev --log-prefix=none" \
      "turbo run trigger:dev --log-prefix=none" \
      "turbo run hook:github --log-prefix=none" \
      "turbo run hook:stripe --log-prefix=none" \
      "node $SCRIPT_DIR/webhook-fanout.js" \
      2>&1 | tee "$LOG_FILE"
  fi
else
  # Fanout already running - connect to existing instance on port 4000
  if [ -n "$AI_AGENT_CMD" ]; then
    concurrently \
      --names "$PREFIX" \
      --prefix-colors "cyan,magenta,yellow,green,blue,red,white,bgMagenta" \
      "PORT=$WEBAPP_PORT turbo run web:dev --log-prefix=none" \
      "PORT=$SLIDES_PORT turbo run slides:dev --filter=@classmoji/slides --log-prefix=none" \
      "PORT=$PAGES_PORT turbo run pages:dev --filter=@classmoji/pages --log-prefix=none" \
      "PORT=$HOOK_PORT turbo run hook:dev --log-prefix=none" \
      "turbo run trigger:dev --log-prefix=none" \
      "turbo run hook:github --log-prefix=none" \
      "turbo run hook:stripe --log-prefix=none" \
      "$AI_AGENT_CMD" \
      2>&1 | tee "$LOG_FILE"
  else
    concurrently \
      --names "$PREFIX" \
      --prefix-colors "cyan,magenta,yellow,green,blue,red,white,bgMagenta" \
      "PORT=$WEBAPP_PORT turbo run web:dev --log-prefix=none" \
      "PORT=$SLIDES_PORT turbo run slides:dev --filter=@classmoji/slides --log-prefix=none" \
      "PORT=$PAGES_PORT turbo run pages:dev --filter=@classmoji/pages --log-prefix=none" \
      "PORT=$HOOK_PORT turbo run hook:dev --log-prefix=none" \
      "turbo run trigger:dev --log-prefix=none" \
      "turbo run hook:github --log-prefix=none" \
      "turbo run hook:stripe --log-prefix=none" \
      2>&1 | tee "$LOG_FILE"
  fi
fi
