import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

export interface DevContext {
  webappUrl: string;
  apiUrl: string;
  quizAgentUrl: string;
  databaseUrl: string;
  devportName: string;
}

/**
 * Read environment configuration from .dev-context file
 * This file is auto-generated by `npm run dev` and contains the actual ports
 * for all services in the current devport configuration.
 */
export function getDevContext(): DevContext {
  // Try multiple paths to handle different CWD scenarios:
  // 1. From repo root: .dev-context
  // 2. From apps/webapp: ../../.dev-context
  const possiblePaths = [
    join(process.cwd(), '.dev-context'),           // Repo root
    join(process.cwd(), '../../.dev-context'),     // From apps/webapp
    join(process.cwd(), '../../../.dev-context'),  // From apps/webapp/tests
  ];

  let devContextPath: string | null = null;
  for (const p of possiblePaths) {
    if (existsSync(p)) {
      devContextPath = p;
      break;
    }
  }

  if (devContextPath) {
    const content = readFileSync(devContextPath, 'utf-8');

    const webappMatch = content.match(/Webapp:\s+(http:\/\/localhost:\d+)/);
    const apiMatch = content.match(/API:\s+(http:\/\/localhost:\d+)/);
    const quizAgentMatch = content.match(/Quiz Agent:\s+(http:\/\/localhost:\d+)/);
    const dbMatch = content.match(/URL:\s+(postgresql:\/\/[^\s]+)/);
    const devportMatch = content.match(/DEVPORT_NAME=(\S+)/);

    return {
      webappUrl: webappMatch?.[1] || process.env.WEBAPP_URL || 'http://localhost:3000',
      apiUrl: apiMatch?.[1] || process.env.API_URL || 'http://localhost:5000',
      quizAgentUrl: quizAgentMatch?.[1] || process.env.QUIZ_AGENT_URL || 'http://localhost:6000',
      databaseUrl: dbMatch?.[1] || process.env.DATABASE_URL || '',
      devportName: devportMatch?.[1] || 'default',
    };
  }

  // Fallback for CI or when .dev-context doesn't exist
  return {
    webappUrl: process.env.WEBAPP_URL || 'http://localhost:3000',
    apiUrl: process.env.API_URL || 'http://localhost:5000',
    quizAgentUrl: process.env.QUIZ_AGENT_URL || 'http://localhost:6000',
    databaseUrl: process.env.DATABASE_URL || '',
    devportName: process.env.DEVPORT_NAME || 'ci',
  };
}

/**
 * Get the base URL for Playwright tests
 */
export function getBaseUrl(): string {
  return getDevContext().webappUrl;
}

/**
 * Test classroom slug - used in URLs: /admin/{classroom-slug}/dashboard
 * This should match the classroom slug in your database (run `npm run db:seed` to create it)
 */
export const TEST_CLASSROOM = process.env.TEST_CLASSROOM || 'classmoji-dev-winter-2025';

/**
 * Test classroom name - displayed on classroom cards in the UI
 * Used to identify the correct classroom when users have multiple classrooms
 */
export const TEST_CLASSROOM_NAME = process.env.TEST_CLASSROOM_NAME || 'Classmoji Dev';

/**
 * Test git organization login - displayed on classroom cards in the UI
 * The select-organization page shows @{git-org-login} on the cards
 */
export const TEST_GIT_ORG = process.env.TEST_GIT_ORG || 'classmoji-development';

/**
 * @deprecated Use TEST_CLASSROOM for URLs or TEST_GIT_ORG for UI text matching
 */
export const TEST_ORG = TEST_CLASSROOM;

/**
 * @deprecated Use ROLE_TEST_USERS instead for role-specific testing
 */
export const TEST_USER = {
  id: '220514774',
  login: 'prof-classmoji',
  name: 'Professor',
  email: 'prof.classmoji@gmail.com',
};

/**
 * Role-specific test users.
 * Each role uses a different GitHub account for realistic permission testing.
 *
 * Token env vars:
 * - GITHUB_PROF_TOKEN: For admin/owner role
 * - GITHUB_TA_TOKEN: For TA/assistant role
 * - GITHUB_STUDENT_TOKEN: For student role
 */
export const ROLE_TEST_USERS = {
  owner: {
    id: '220514774',
    login: 'prof-classmoji',
    name: 'Professor',
    tokenEnvVar: 'GITHUB_PROF_TOKEN',
  },
  assistant: {
    id: process.env.TEST_TA_USER_ID || '220514774', // Configure in env for real TA user
    login: process.env.TEST_TA_USER_LOGIN || 'prof-classmoji',
    name: 'Teaching Assistant',
    tokenEnvVar: 'GITHUB_TA_TOKEN',
  },
  student: {
    id: process.env.TEST_STUDENT_USER_ID || '220514774', // Configure in env for real student user
    login: process.env.TEST_STUDENT_USER_LOGIN || 'prof-classmoji',
    name: 'Student',
    tokenEnvVar: 'GITHUB_STUDENT_TOKEN',
  },
} as const;

export type TestRole = keyof typeof ROLE_TEST_USERS;
