import { BRAND, BRAND_LIGHT, BRAND_DARK, BRAND_TEXT, PRIMARY } from './theme.js';

const darkTheme = {
  token: {
    colorPrimary: BRAND,
    colorTextBase: '#f1f2f6',
    colorBgBase: '#171a25',
    colorBgContainer: '#121521',
    colorBgElevated: '#171a25',
    colorBgLayout: '#0e1016',
    colorBorder: '#262a38',
    colorBorderSecondary: '#171a25',
    colorText: '#f1f2f6',
    colorTextSecondary: '#a4a9b8',
    colorTextTertiary: '#7a7f8e',
    colorTextQuaternary: '#323648',
    colorLink: BRAND,
    colorLinkHover: BRAND_LIGHT,
    colorLinkActive: BRAND_DARK,
    colorBgSolidActive: BRAND,
    colorSuccess: PRIMARY,
    colorWarning: '#f59e0b',
    colorError: '#ef4444',
    colorInfo: '#3b82f6',
  },
  components: {
    Button: {
      algorithm: true,
      colorBgContainer: BRAND,
      colorText: BRAND_TEXT,
      colorBorder: BRAND,
      colorBgContainerHover: BRAND_LIGHT,
      colorTextHover: BRAND_TEXT,
      colorBorderHover: BRAND_LIGHT,
      primaryColor: BRAND_TEXT,
      defaultHoverColor: BRAND_TEXT,
      defaultBg: '#171a25',
      defaultBorderColor: '#262a38',
      defaultColor: '#f1f2f6',
      defaultHoverBg: '#262a38',
      defaultHoverBorderColor: '#323648',
      // Remove box shadow
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Table: {
      headerBg: '#171a25',
      headerColor: '#f1f2f6',
      headerSortActiveBg: '#262a38',
      headerSortHoverBg: '#262a38',
      bodySortBg: '#121521',
      rowSelectedBg: '#262a38',
      rowSelectedHoverBg: '#323648',
      rowHoverBg: '#171a25',
      colorBgContainer: '#121521',
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
      borderColor: '#262a38',
      headerBorderRadius: 8,
    },
    Tabs: {
      colorText: '#a4a9b8',
      colorTextActive: '#f1f2f6',
      colorPrimary: PRIMARY,
      colorPrimaryHover: PRIMARY,
      colorPrimaryActive: PRIMARY,
      colorBgContainer: 'transparent',
      itemColor: '#a4a9b8',
      itemSelectedColor: PRIMARY,
      itemHoverColor: PRIMARY,
      itemActiveColor: PRIMARY,
      inkBarColor: PRIMARY,
      titleFontSize: 14,
      cardBg: '#171a25',
    },
    Tag: {
      bordered: false,
      defaultBg: '#171a25',
      defaultColor: '#f1f2f6',
    },
    Progress: {
      defaultColor: BRAND_LIGHT,
      colorSuccess: BRAND,
      remainingColor: '#262a38',
      circleTextColor: '#f1f2f6',
    },
    Select: {
      optionSelectedBg: '#262a38',
      optionActiveBg: '#171a25',
      optionSelectedFontWeight: 600,
      optionSelectedColor: BRAND,
      selectorBg: '#171a25',
      colorText: '#f1f2f6',
      colorTextPlaceholder: '#7a7f8e',
      colorBorder: '#262a38',
      colorBgContainer: '#171a25',
      colorBgElevated: '#121521',
      controlItemBgActive: '#262a38',
      controlItemBgHover: '#171a25',
      multipleItemBg: '#262a38',
    },
    Input: {
      colorBgContainer: '#171a25',
      colorText: '#f1f2f6',
      colorTextPlaceholder: '#7a7f8e',
      colorBorder: '#262a38',
      colorBgContainerDisabled: '#121521',
      colorTextDisabled: '#323648',
      addonBg: '#121521',
      hoverBorderColor: '#323648',
      activeBorderColor: BRAND,
    },
    Modal: {
      contentBg: '#171a25',
      headerBg: '#171a25',
      titleColor: '#f1f2f6',
      colorText: '#f1f2f6',
      footerBg: 'transparent',
    },
    Dropdown: {
      colorBgElevated: '#171a25',
      colorText: '#f1f2f6',
      controlItemBgHover: '#262a38',
      controlItemBgActive: '#323648',
    },
    Card: {
      colorBgContainer: '#171a25',
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
      colorBorderSecondary: '#262a38',
    },
    Tooltip: {
      colorBgSpotlight: '#262a38',
      colorTextLightSolid: '#f1f2f6',
    },
    DatePicker: {
      colorBgContainer: '#171a25',
      colorBgElevated: '#121521',
      colorText: '#f1f2f6',
      colorTextPlaceholder: '#7a7f8e',
      colorBorder: '#262a38',
      hoverBorderColor: '#323648',
      activeBorderColor: BRAND,
      cellHoverBg: '#262a38',
      cellActiveWithRangeBg: '#262a38',
      cellRangeBorderColor: 'transparent',
      cellBgDisabled: '#121521',
      cellRangeHoverBg: '#323648',
    },
    Checkbox: {
      colorBgContainer: '#171a25',
      colorBorder: '#262a38',
      colorWhite: '#121521',
    },
    Radio: {
      colorBgContainer: '#171a25',
      colorBorder: '#262a38',
      buttonSolidCheckedBg: BRAND,
      buttonSolidCheckedColor: BRAND_TEXT,
      dotColorDisabled: '#323648',
    },
    Switch: {
      colorPrimary: BRAND,
      colorPrimaryHover: BRAND_LIGHT,
      colorTextTertiary: '#7a7f8e',
      colorTextQuaternary: '#323648',
      handleBg: '#f1f2f6',
    },
    Form: {
      labelColor: '#f1f2f6',
    },
    Layout: {
      bodyBg: '#0e1016',
      headerBg: '#121521',
      siderBg: '#121521',
      triggerBg: '#171a25',
      triggerColor: '#f1f2f6',
    },
    Menu: {
      colorBgContainer: '#121521',
      itemBg: 'transparent',
      itemColor: '#a4a9b8',
      itemHoverBg: '#171a25',
      itemHoverColor: '#f1f2f6',
      itemSelectedBg: '#262a38',
      itemSelectedColor: BRAND,
      itemActiveBg: '#262a38',
      subMenuItemBg: '#121521',
      darkItemBg: '#121521',
      darkItemColor: '#a4a9b8',
      darkItemHoverBg: '#171a25',
      darkItemSelectedBg: '#262a38',
      darkItemSelectedColor: BRAND,
    },
    Divider: {
      colorSplit: '#262a38',
    },
    Avatar: {
      colorTextPlaceholder: '#a4a9b8',
      containerSize: 32,
      groupOverlapping: -8,
    },
    Badge: {
      colorBgContainer: '#ef4444',
      colorError: '#ef4444',
      colorSuccess: PRIMARY,
      colorWarning: '#f59e0b',
      colorInfo: '#3b82f6',
      textFontWeight: 600,
    },
    Notification: {
      colorBgElevated: '#171a25',
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
      colorIcon: '#a4a9b8',
      colorIconHover: '#f1f2f6',
    },
    Message: {
      contentBg: '#171a25',
      colorText: '#f1f2f6',
    },
    Spin: {
      colorPrimary: BRAND,
      colorText: '#f1f2f6',
    },
    Skeleton: {
      colorFill: '#262a38',
      colorFillContent: '#171a25',
    },
    Empty: {
      colorText: '#a4a9b8',
      colorTextDescription: '#7a7f8e',
    },
    Statistic: {
      colorText: '#f1f2f6',
      titleColor: '#a4a9b8',
    },
    Collapse: {
      headerBg: '#171a25',
      contentBg: '#121521',
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
      colorBorder: '#262a38',
    },
    Alert: {
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
    },
    Timeline: {
      colorText: '#f1f2f6',
      colorBgContainer: '#171a25',
      colorBorder: '#262a38',
      dotBg: '#121521',
    },
    Segmented: {
      colorBgLayout: '#171a25',
      colorBgElevated: '#262a38',
      colorText: '#f1f2f6',
      colorTextLabel: '#a4a9b8',
      itemSelectedBg: BRAND,
      itemSelectedColor: BRAND_TEXT,
      itemHoverBg: '#262a38',
      itemHoverColor: '#f1f2f6',
      itemActiveBg: '#323648',
    },
    Steps: {
      colorText: '#f1f2f6',
      colorTextDescription: '#a4a9b8',
      colorBgContainer: '#171a25',
      colorBorderSecondary: '#262a38',
      colorSplit: '#262a38',
      dotCurrentSize: 10,
      titleLineHeight: 1.2,
    },
    Upload: {
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
      colorBgContainer: '#171a25',
      colorBorder: '#262a38',
      colorFillAlter: '#121521',
    },
    Tree: {
      colorText: '#f1f2f6',
      colorTextDescription: '#a4a9b8',
      colorBgContainer: '#121521',
      nodeHoverBg: '#171a25',
      nodeSelectedBg: '#262a38',
    },
    TreeSelect: {
      colorBgContainer: '#171a25',
      colorBgElevated: '#121521',
      colorText: '#f1f2f6',
      colorTextPlaceholder: '#7a7f8e',
      colorBorder: '#262a38',
      nodeHoverBg: '#262a38',
      nodeSelectedBg: '#323648',
    },
    Anchor: {
      colorText: '#a4a9b8',
      colorPrimary: BRAND,
      linkPaddingBlock: 4,
      linkPaddingInlineStart: 16,
    },
    Drawer: {
      colorBgElevated: '#171a25',
      colorBgMask: 'rgba(0, 0, 0, 0.6)',
      colorText: '#f1f2f6',
    },
    Popover: {
      colorBgElevated: '#171a25',
      colorText: '#f1f2f6',
      titleMinWidth: 177,
    },
    Popconfirm: {
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
    },
    Rate: {
      colorText: '#7a7f8e',
      colorFillContent: '#262a38',
      starSize: 20,
    },
    Mentions: {
      colorBgContainer: '#171a25',
      colorBgElevated: '#121521',
      colorText: '#f1f2f6',
      colorTextPlaceholder: '#7a7f8e',
      colorBorder: '#262a38',
      controlItemBgHover: '#262a38',
    },
    AutoComplete: {
      colorBgContainer: '#171a25',
      colorBgElevated: '#121521',
      colorText: '#f1f2f6',
      colorTextPlaceholder: '#7a7f8e',
      colorBorder: '#262a38',
    },
    Cascader: {
      colorBgContainer: '#171a25',
      colorBgElevated: '#121521',
      controlItemBgHover: '#262a38',
      controlItemBgActive: '#323648',
      colorText: '#f1f2f6',
      colorTextPlaceholder: '#7a7f8e',
      colorBorder: '#262a38',
    },
    Slider: {
      trackBg: '#262a38',
      trackHoverBg: '#323648',
      trackBgDisabled: '#171a25',
      railBg: '#262a38',
      railHoverBg: '#323648',
      handleColor: BRAND,
      handleActiveColor: BRAND_LIGHT,
      dotBorderColor: '#262a38',
      dotActiveBorderColor: BRAND,
    },
    Typography: {
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
      colorTextDescription: '#a4a9b8',
      colorTextSecondary: '#a4a9b8',
      colorTextDisabled: '#7a7f8e',
      colorLink: BRAND,
      colorLinkHover: BRAND_LIGHT,
      colorLinkActive: BRAND_DARK,
    },
    Breadcrumb: {
      colorText: '#a4a9b8',
      colorTextDescription: '#a4a9b8',
      colorBgTextHover: '#171a25',
      itemColor: '#a4a9b8',
      lastItemColor: '#f1f2f6',
      linkColor: '#a4a9b8',
      linkHoverColor: BRAND,
      separatorColor: '#7a7f8e',
    },
    List: {
      colorText: '#f1f2f6',
      colorTextDescription: '#a4a9b8',
      colorTextDisabled: '#7a7f8e',
      itemPaddingLG: '16px 24px',
      colorSplit: '#262a38',
      itemHoverBg: '#171a25',
    },
    Descriptions: {
      colorText: '#f1f2f6',
      colorTextSecondary: '#a4a9b8',
      colorFillAlter: '#171a25',
      colorSplit: '#262a38',
      labelBg: '#121521',
    },
    Result: {
      colorText: '#f1f2f6',
      colorTextHeading: '#f1f2f6',
      colorTextDescription: '#a4a9b8',
      colorSuccess: PRIMARY,
      colorError: '#ef4444',
      colorWarning: '#f59e0b',
      colorInfo: '#3b82f6',
    },
    Transfer: {
      colorBgContainer: '#171a25',
      colorBorder: '#262a38',
      colorText: '#f1f2f6',
      colorTextDisabled: '#7a7f8e',
      itemHoverBg: '#262a38',
      itemSelectedBg: '#323648',
      headerBg: '#121521',
    },
    Comment: {
      colorText: '#f1f2f6',
      colorTextSecondary: '#a4a9b8',
      colorTextTertiary: '#7a7f8e',
      actionColor: '#a4a9b8',
      actionHoverColor: BRAND,
      authorNameColor: '#f1f2f6',
      authorTimeColor: '#a4a9b8',
      avatarBg: '#262a38',
      contentBg: '#171a25',
    },
    BackTop: {
      colorText: '#f1f2f6',
      colorTextLightSolid: BRAND_TEXT,
      colorBgElevated: BRAND,
    },
    Image: {
      colorBgMask: 'rgba(0, 0, 0, 0.85)',
      colorTextLightSolid: '#f1f2f6',
      previewOperationColor: '#a4a9b8',
      previewOperationColorHover: '#f1f2f6',
      previewOperationColorDisabled: '#323648',
    },
    Carousel: {
      colorBgContainer: '#171a25',
      dotWidth: 16,
      dotHeight: 3,
      dotActiveWidth: 24,
    },
    Calendar: {
      colorBgContainer: '#171a25',
      colorBgDateSelected: '#262a38',
      colorText: '#f1f2f6',
      colorTextDisabled: '#7a7f8e',
      colorBorder: '#262a38',
      colorSplit: '#262a38',
      colorBgHeader: '#121521',
      colorTextHeading: '#f1f2f6',
    },
    FloatButton: {
      colorText: BRAND_TEXT,
      colorBgElevated: BRAND,
      colorTextLightSolid: BRAND_TEXT,
    },
  },
};

export default darkTheme;
