import { BRAND, BRAND_LIGHT, BRAND_DARK, BRAND_TEXT, PRIMARY, PRIMARY_600, SECONDARY } from './theme.js';

const darkTheme = {
  token: {
    colorPrimary: BRAND,
    colorTextBase: '#e5e7eb',
    colorBgBase: '#1f2937',
    colorBgContainer: '#111827',
    colorBgElevated: '#1f2937',
    colorBgLayout: '#0f1419',
    colorBorder: '#374151',
    colorBorderSecondary: '#1f2937',
    colorText: '#e5e7eb',
    colorTextSecondary: '#9ca3af',
    colorTextTertiary: '#6b7280',
    colorTextQuaternary: '#4b5563',
    colorLink: BRAND,
    colorLinkHover: BRAND_LIGHT,
    colorLinkActive: BRAND_DARK,
    colorBgSolidActive: BRAND,
    colorSuccess: PRIMARY,
    colorWarning: '#f59e0b',
    colorError: '#ef4444',
    colorInfo: '#3b82f6',
  },
  components: {
    Button: {
      algorithm: true,
      colorBgContainer: BRAND,
      colorText: BRAND_TEXT,
      colorBorder: BRAND,
      colorBgContainerHover: BRAND_LIGHT,
      colorTextHover: BRAND_TEXT,
      colorBorderHover: BRAND_LIGHT,
      primaryColor: BRAND_TEXT,
      defaultHoverColor: BRAND_TEXT,
      defaultBg: '#1f2937',
      defaultBorderColor: '#374151',
      defaultColor: '#e5e7eb',
      defaultHoverBg: '#374151',
      defaultHoverBorderColor: '#4b5563',
      // Remove box shadow
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Table: {
      headerBg: '#1f2937',
      headerColor: '#e5e7eb',
      headerSortActiveBg: '#374151',
      headerSortHoverBg: '#374151',
      bodySortBg: '#111827',
      rowSelectedBg: '#374151',
      rowSelectedHoverBg: '#4b5563',
      rowHoverBg: '#1f2937',
      colorBgContainer: '#111827',
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
      borderColor: '#374151',
      headerBorderRadius: 8,
    },
    Tabs: {
      colorText: '#9ca3af',
      colorTextActive: '#e5e7eb',
      colorPrimary: PRIMARY,
      colorPrimaryHover: PRIMARY,
      colorPrimaryActive: PRIMARY,
      colorBgContainer: 'transparent',
      itemColor: '#9ca3af',
      itemSelectedColor: PRIMARY,
      itemHoverColor: PRIMARY,
      itemActiveColor: PRIMARY,
      inkBarColor: PRIMARY,
      titleFontSize: 14,
      cardBg: '#1f2937',
    },
    Tag: {
      bordered: false,
      defaultBg: '#1f2937',
      defaultColor: '#e5e7eb',
    },
    Progress: {
      defaultColor: BRAND_LIGHT,
      colorSuccess: BRAND,
      remainingColor: '#374151',
      circleTextColor: '#e5e7eb',
    },
    Select: {
      optionSelectedBg: '#374151',
      optionActiveBg: '#1f2937',
      optionSelectedFontWeight: 600,
      optionSelectedColor: BRAND,
      selectorBg: '#1f2937',
      colorText: '#e5e7eb',
      colorTextPlaceholder: '#6b7280',
      colorBorder: '#374151',
      colorBgContainer: '#1f2937',
      colorBgElevated: '#111827',
      controlItemBgActive: '#374151',
      controlItemBgHover: '#1f2937',
      multipleItemBg: '#374151',
    },
    Input: {
      colorBgContainer: '#1f2937',
      colorText: '#e5e7eb',
      colorTextPlaceholder: '#6b7280',
      colorBorder: '#374151',
      colorBgContainerDisabled: '#111827',
      colorTextDisabled: '#4b5563',
      addonBg: '#111827',
      hoverBorderColor: '#4b5563',
      activeBorderColor: BRAND,
    },
    Modal: {
      contentBg: '#1f2937',
      headerBg: '#1f2937',
      titleColor: '#e5e7eb',
      colorText: '#e5e7eb',
      footerBg: 'transparent',
    },
    Dropdown: {
      colorBgElevated: '#1f2937',
      colorText: '#e5e7eb',
      controlItemBgHover: '#374151',
      controlItemBgActive: '#4b5563',
    },
    Card: {
      colorBgContainer: '#1f2937',
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
      colorBorderSecondary: '#374151',
    },
    Tooltip: {
      colorBgSpotlight: '#374151',
      colorTextLightSolid: '#e5e7eb',
    },
    DatePicker: {
      colorBgContainer: '#1f2937',
      colorBgElevated: '#111827',
      colorText: '#e5e7eb',
      colorTextPlaceholder: '#6b7280',
      colorBorder: '#374151',
      hoverBorderColor: '#4b5563',
      activeBorderColor: BRAND,
      cellHoverBg: '#374151',
      cellActiveWithRangeBg: '#374151',
      cellRangeBorderColor: 'transparent',
      cellBgDisabled: '#111827',
      cellRangeHoverBg: '#4b5563',
    },
    Checkbox: {
      colorBgContainer: '#1f2937',
      colorBorder: '#374151',
      colorWhite: '#111827',
    },
    Radio: {
      colorBgContainer: '#1f2937',
      colorBorder: '#374151',
      buttonSolidCheckedBg: BRAND,
      buttonSolidCheckedColor: BRAND_TEXT,
      dotColorDisabled: '#4b5563',
    },
    Switch: {
      colorPrimary: BRAND,
      colorPrimaryHover: BRAND_LIGHT,
      colorTextTertiary: '#6b7280',
      colorTextQuaternary: '#4b5563',
      handleBg: '#e5e7eb',
    },
    Form: {
      labelColor: '#e5e7eb',
    },
    Layout: {
      bodyBg: '#0f1419',
      headerBg: '#111827',
      siderBg: '#111827',
      triggerBg: '#1f2937',
      triggerColor: '#e5e7eb',
    },
    Menu: {
      colorBgContainer: '#111827',
      itemBg: 'transparent',
      itemColor: '#9ca3af',
      itemHoverBg: '#1f2937',
      itemHoverColor: '#e5e7eb',
      itemSelectedBg: '#374151',
      itemSelectedColor: BRAND,
      itemActiveBg: '#374151',
      subMenuItemBg: '#111827',
      darkItemBg: '#111827',
      darkItemColor: '#9ca3af',
      darkItemHoverBg: '#1f2937',
      darkItemSelectedBg: '#374151',
      darkItemSelectedColor: BRAND,
    },
    Divider: {
      colorSplit: '#374151',
    },
    Avatar: {
      colorTextPlaceholder: '#9ca3af',
      containerSize: 32,
      groupOverlapping: -8,
    },
    Badge: {
      colorBgContainer: '#ef4444',
      colorError: '#ef4444',
      colorSuccess: PRIMARY,
      colorWarning: '#f59e0b',
      colorInfo: '#3b82f6',
      textFontWeight: 600,
    },
    Notification: {
      colorBgElevated: '#1f2937',
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
      colorIcon: '#9ca3af',
      colorIconHover: '#e5e7eb',
    },
    Message: {
      contentBg: '#1f2937',
      colorText: '#e5e7eb',
    },
    Spin: {
      colorPrimary: BRAND,
      colorText: '#e5e7eb',
    },
    Skeleton: {
      colorFill: '#374151',
      colorFillContent: '#1f2937',
    },
    Empty: {
      colorText: '#9ca3af',
      colorTextDescription: '#6b7280',
    },
    Statistic: {
      colorText: '#e5e7eb',
      titleColor: '#9ca3af',
    },
    Collapse: {
      headerBg: '#1f2937',
      contentBg: '#111827',
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
      colorBorder: '#374151',
    },
    Alert: {
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
    },
    Timeline: {
      colorText: '#e5e7eb',
      colorBgContainer: '#1f2937',
      colorBorder: '#374151',
      dotBg: '#111827',
    },
    Segmented: {
      colorBgLayout: '#1f2937',
      colorBgElevated: '#374151',
      colorText: '#e5e7eb',
      colorTextLabel: '#9ca3af',
      itemSelectedBg: BRAND,
      itemSelectedColor: BRAND_TEXT,
      itemHoverBg: '#374151',
      itemHoverColor: '#e5e7eb',
      itemActiveBg: '#4b5563',
    },
    Steps: {
      colorText: '#e5e7eb',
      colorTextDescription: '#9ca3af',
      colorBgContainer: '#1f2937',
      colorBorderSecondary: '#374151',
      colorSplit: '#374151',
      dotCurrentSize: 10,
      titleLineHeight: 1.2,
    },
    Upload: {
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
      colorBgContainer: '#1f2937',
      colorBorder: '#374151',
      colorFillAlter: '#111827',
    },
    Tree: {
      colorText: '#e5e7eb',
      colorTextDescription: '#9ca3af',
      colorBgContainer: '#111827',
      nodeHoverBg: '#1f2937',
      nodeSelectedBg: '#374151',
    },
    TreeSelect: {
      colorBgContainer: '#1f2937',
      colorBgElevated: '#111827',
      colorText: '#e5e7eb',
      colorTextPlaceholder: '#6b7280',
      colorBorder: '#374151',
      nodeHoverBg: '#374151',
      nodeSelectedBg: '#4b5563',
    },
    Anchor: {
      colorText: '#9ca3af',
      colorPrimary: BRAND,
      linkPaddingBlock: 4,
      linkPaddingInlineStart: 16,
    },
    Drawer: {
      colorBgElevated: '#1f2937',
      colorBgMask: 'rgba(0, 0, 0, 0.6)',
      colorText: '#e5e7eb',
    },
    Popover: {
      colorBgElevated: '#1f2937',
      colorText: '#e5e7eb',
      titleMinWidth: 177,
    },
    Popconfirm: {
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
    },
    Rate: {
      colorText: '#6b7280',
      colorFillContent: '#374151',
      starSize: 20,
    },
    Mentions: {
      colorBgContainer: '#1f2937',
      colorBgElevated: '#111827',
      colorText: '#e5e7eb',
      colorTextPlaceholder: '#6b7280',
      colorBorder: '#374151',
      controlItemBgHover: '#374151',
    },
    AutoComplete: {
      colorBgContainer: '#1f2937',
      colorBgElevated: '#111827',
      colorText: '#e5e7eb',
      colorTextPlaceholder: '#6b7280',
      colorBorder: '#374151',
    },
    Cascader: {
      colorBgContainer: '#1f2937',
      colorBgElevated: '#111827',
      controlItemBgHover: '#374151',
      controlItemBgActive: '#4b5563',
      colorText: '#e5e7eb',
      colorTextPlaceholder: '#6b7280',
      colorBorder: '#374151',
    },
    Slider: {
      trackBg: '#374151',
      trackHoverBg: '#4b5563',
      trackBgDisabled: '#1f2937',
      railBg: '#374151',
      railHoverBg: '#4b5563',
      handleColor: BRAND,
      handleActiveColor: BRAND_LIGHT,
      dotBorderColor: '#374151',
      dotActiveBorderColor: BRAND,
    },
    Typography: {
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
      colorTextDescription: '#9ca3af',
      colorTextSecondary: '#9ca3af',
      colorTextDisabled: '#6b7280',
      colorLink: BRAND,
      colorLinkHover: BRAND_LIGHT,
      colorLinkActive: BRAND_DARK,
    },
    Breadcrumb: {
      colorText: '#9ca3af',
      colorTextDescription: '#9ca3af',
      colorBgTextHover: '#1f2937',
      itemColor: '#9ca3af',
      lastItemColor: '#e5e7eb',
      linkColor: '#9ca3af',
      linkHoverColor: BRAND,
      separatorColor: '#6b7280',
    },
    List: {
      colorText: '#e5e7eb',
      colorTextDescription: '#9ca3af',
      colorTextDisabled: '#6b7280',
      itemPaddingLG: '16px 24px',
      colorSplit: '#374151',
      itemHoverBg: '#1f2937',
    },
    Descriptions: {
      colorText: '#e5e7eb',
      colorTextSecondary: '#9ca3af',
      colorFillAlter: '#1f2937',
      colorSplit: '#374151',
      labelBg: '#111827',
    },
    Result: {
      colorText: '#e5e7eb',
      colorTextHeading: '#e5e7eb',
      colorTextDescription: '#9ca3af',
      colorSuccess: PRIMARY,
      colorError: '#ef4444',
      colorWarning: '#f59e0b',
      colorInfo: '#3b82f6',
    },
    Transfer: {
      colorBgContainer: '#1f2937',
      colorBorder: '#374151',
      colorText: '#e5e7eb',
      colorTextDisabled: '#6b7280',
      itemHoverBg: '#374151',
      itemSelectedBg: '#4b5563',
      headerBg: '#111827',
    },
    Comment: {
      colorText: '#e5e7eb',
      colorTextSecondary: '#9ca3af',
      colorTextTertiary: '#6b7280',
      actionColor: '#9ca3af',
      actionHoverColor: BRAND,
      authorNameColor: '#e5e7eb',
      authorTimeColor: '#9ca3af',
      avatarBg: '#374151',
      contentBg: '#1f2937',
    },
    BackTop: {
      colorText: '#e5e7eb',
      colorTextLightSolid: BRAND_TEXT,
      colorBgElevated: BRAND,
    },
    Image: {
      colorBgMask: 'rgba(0, 0, 0, 0.85)',
      colorTextLightSolid: '#e5e7eb',
      previewOperationColor: '#9ca3af',
      previewOperationColorHover: '#e5e7eb',
      previewOperationColorDisabled: '#4b5563',
    },
    Carousel: {
      colorBgContainer: '#1f2937',
      dotWidth: 16,
      dotHeight: 3,
      dotActiveWidth: 24,
    },
    Calendar: {
      colorBgContainer: '#1f2937',
      colorBgDateSelected: '#374151',
      colorText: '#e5e7eb',
      colorTextDisabled: '#6b7280',
      colorBorder: '#374151',
      colorSplit: '#374151',
      colorBgHeader: '#111827',
      colorTextHeading: '#e5e7eb',
    },
    FloatButton: {
      colorText: BRAND_TEXT,
      colorBgElevated: BRAND,
      colorTextLightSolid: BRAND_TEXT,
    },
  },
};

export default darkTheme;
